// Lista de estilos para 103 FINDER
// Exporta SIEMPRE "STYLES" para que el import funcione.

export const STYLES: string[] = [
  "Pop Rock", "House", "Vocal", "Experimental", "Punk", "Alternative Rock", "Synth-pop",
  "Techno", "Indie Rock", "Ambient", "Soul", "Disco", "Hardcore", "Folk", "Ballad", "Country",
  "Hard Rock", "Electro", "Rock & Roll", "Chanson", "Romantic", "Trance", "Heavy Metal",
  "Psychedelic Rock", "Folk Rock", "Soundtrack", "Downtempo", "Noise", "Schlager", "Prog Rock",
  "Funk", "Classic Rock", "Easy Listening", "Black Metal", "Tech House", "Blues Rock", "Deep House",
  "Rhythm & Blues", "New Wave", "Industrial", "Classical", "Death Metal", "Progressive House",
  "Drum n Bass", "Euro House", "Soft Rock", "Garage Rock", "Abstract", "Gospel", "Europop",
  "Minimal", "Acoustic", "Baroque", "Thrash", "Modern", "Swing", "Big Band", "Indie Pop", "Dub",
  "Country Rock", "Drone", "Contemporary Jazz", "Breakbeat", "Progressive Trance", "Opera",
  "Holiday", "Contemporary", "IDM", "Dancehall", "African", "Breaks", "Contemporary R&B",
  "Dark Ambient", "Art Rock", "Post-Punk", "Reggae", "Fusion", "Gangsta", "Dance-pop", "Doom Metal",
  "Religious", "Pop Rap", "Avantgarde", "RnB/Swing", "Beat", "Electro House", "Acid",
  "Instrumental", "Hard Trance", "Rockabilly", "Score", "Jazz-Funk", "Comedy", "Lo-Fi",
  "Roots Reggae", "Theme", "Grindcore", "Leftfield", "Ska", "Post Rock", "Spoken Word", "Bolero",
  "Soul-Jazz", "Psy-Trance", "Power Pop", "Dubstep", "Glam", "Salsa", "New Age", "Bop", "Hip Hop",
  "Conscious", "Goth Rock", "Modern Classical", "Jazz-Rock", "Cumbia", "Hard House", "Emo",
  "Free Improvisation", "J-pop", "Musical", "Trip Hop", "Latin Jazz", "Stoner Rock", "Volksmusik",
  "EBM", "Italo-Disco", "Shoegaze", "MPB", "Choral", "Jungle", "Surf", "Doo Wop", "Hard Bop",
  "Field Recording", "Story", "Hardstyle", "Synthwave", "Free Jazz", "Pop Punk", "Tango", "Samba",
  "Oi", "Trap", "Garage House", "Darkwave", "Radioplay", "Celtic", "Cool Jazz", "Bluegrass",
  "Vaporwave", "Post Bop", "Laïkó", "Eurodance", "Metalcore", "Happy Hardcore", "UK Garage",
  "Tribal", "Polka", "Novelty", "Smooth Jazz", "Hardcore Hip-Hop", "Grunge", "Flamenco",
  "Progressive Metal", "Italodance", "Kayōkyoku", "AOR", "Dixieland", "Arena Rock", "Nu Metal",
  "Southern Rock", "Symphonic Rock", "Boom Bap", "Hindustani", "Rumba", "Latin", "Parody",
  "Future Jazz", "Glitch", "Harsh Noise Wall", "Cha-Cha", "Power Metal", "Audiobook", "Merengue",
  "Space Rock", "Dub Techno", "Krautrock", "Bossa Nova", "Gabber", "Speed Metal", "Neo-Classical",
  "Breakcore", "Post-Hardcore", "Ranchera", "Hi NRG", "Jazzy Hip-Hop", "Poetry", "Reggae-Pop",
  "Power Electronics", "Avant-garde Jazz", "Bollywood", "Acid House", "Boogie", "Dungeon Synth",
  "Marches", "Renaissance", "Minimal Techno", "Musique Concrète", "Sludge Metal", "Electric Blues",
  "Mod", "Mambo", "Nu-Disco", "Chiptune", "Bossanova", "Country Blues", "Bass Music", "Acid Jazz",
  "Freestyle", "Interview", "Thug Rap", "Tribal House", "Berlin-School", "Big Beat", "Math Rock",
  "Indian Classical", "Light Music", "Modal", "Calypso", "Psychedelic", "Chicago Blues",
  "Broken Beat", "Education", "Mandopop", "Neofolk", "Impressionist", "Ethereal", "Rocksteady",
  "Neo Soul", "Crust", "Afrobeat", "Operetta", "Guaracha", "Afro-Cuban", "Video Game Music",
  "Lounge", "Britpop", "Chillwave", "G-Funk", "Grime", "Goregrind", "Hip-House", "Ragtime",
  "Euro-Disco", "Melodic Death Metal", "Goa Trance", "Gothic Metal", "Deep Techno", "Brass Band",
  "Lovers Rock", "Symphonic Metal", "Dream Pop", "Tech Trance", "Hard Techno", "K-pop",
  "Atmospheric Black Metal", "Eurobeat", "City Pop", "Mariachi", "Melodic Hardcore", "Deathcore",
  "Fado", "Funk Metal", "Hands Up", "Sound Collage", "Acid Rock", "Reggaeton", "Zouk", "Makina",
  "Witch House", "Dark Jazz", "UK Funky", "Mathcore", "French House", "Electro Swing", "Hyperpop",
  "Amapiano", "Phonk", "Drill", "Future Bass", "Slowcore", "Ambient House", "Microhouse",
  "Deconstructed Club", "Jersey Club", "Midwest Emo", "Bitpop", "Lowercase", "Anarcho-Punk",
  "Spiritual Jazz", "V-pop", "Kuduro", "Pagode", "Gqom", "Classical Guitar", "Nintendocore",
  "Synthpunk", "Microtonal"
];
