# core/constants.py

GENRES = [
    "Electronic",
    "Rock",
    "Jazz",
    "Funk / Soul",
    "Hip Hop",
    "Pop",
    "Classical",
    "Reggae",
    "Blues",
    "Latin",
]

STYLES = [
    "Pop Rock", "House", "Vocal", "Experimental", "Punk", "Alternative Rock", "Synth-pop", "Techno",
    "Indie Rock", "Ambient", "Soul", "Disco", "Hardcore", "Folk", "Ballad", "Country", "Hard Rock",
    "Electro", "Rock & Roll", "Chanson", "Romantic", "Trance", "Heavy Metal", "Psychedelic Rock",
    "Folk Rock", "Soundtrack", "Downtempo", "Noise", "Schlager", "Prog Rock", "Funk", "Classic Rock",
    "Easy Listening", "Black Metal", "Tech House", "Blues Rock", "Deep House", "Rhythm & Blues",
    "New Wave", "Industrial", "Classical", "Death Metal", "Progressive House", "Drum n Bass",
    "Euro House", "Soft Rock", "Garage Rock", "Abstract", "Gospel", "Europop", "Minimal", "Acoustic",
    "Baroque", "Thrash", "Modern", "Swing", "Big Band", "Indie Pop", "Dub", "Country Rock", "Drone",
    "Contemporary Jazz", "Breakbeat", "Progressive Trance", "Opera", "Holiday", "Contemporary", "IDM",
    "Dancehall", "African", "Breaks", "Contemporary R&B", "Dark Ambient", "Art Rock", "Post-Punk",
    "Reggae", "Fusion", "Gangsta", "Dance-pop", "Doom Metal", "Religious", "Pop Rap", "Avantgarde",
    "RnB/Swing", "Beat", "Electro House", "Acid", "Instrumental", "Hard Trance", "Rockabilly", "Score",
    "Jazz-Funk", "Comedy", "Lo-Fi", "Roots Reggae", "Theme", "Grindcore", "Leftfield", "Ska",
    "Post Rock", "Spoken Word", "Bolero", "Soul-Jazz", "Psy-Trance", "Power Pop", "Dubstep", "Glam",
    "Salsa", "New Age", "Bop", "Hip Hop", "Conscious", "Goth Rock", "Modern Classical", "Jazz-Rock",
    "Cumbia", "Hard House", "Emo", "Free Improvisation", "J-pop", "Musical", "Trip Hop", "Latin Jazz",
    "Stoner Rock", "Volksmusik", "EBM", "Italo-Disco", "Shoegaze", "MPB", "Choral", "Jungle", "Surf",
    "Doo Wop", "Hard Bop", "Field Recording", "Story", "Hardstyle", "Synthwave", "Free Jazz",
    "Pop Punk", "Tango", "Samba", "Oi", "Trap", "Garage House", "Darkwave", "Radioplay", "Celtic",
    "Cool Jazz", "Bluegrass", "Vaporwave", "Post Bop", "Laïkó", "Eurodance", "Metalcore",
    "Happy Hardcore", "UK Garage", "Tribal", "Polka", "Novelty", "Smooth Jazz",
    "Hardcore Hip-Hop", "Grunge", "Flamenco", "Progressive Metal", "Italodance", "Kayōkyoku", "AOR",
    "Dixieland", "Arena Rock", "Nu Metal", "Southern Rock", "Symphonic Rock", "Boom Bap",
    "Hindustani", "Rumba", "Latin", "Parody", "Future Jazz", "Glitch", "Harsh Noise Wall", "Cha-Cha",
    "Power Metal", "Audiobook", "Merengue", "Space Rock", "Dub Techno", "Krautrock", "Bossa Nova",
    "Gabber", "Speed Metal", "Neo-Classical", "Breakcore", "Post-Hardcore", "Ranchera", "Hi NRG",
    "Jazzy Hip-Hop", "Poetry", "Reggae-Pop", "Power Electronics", "Avant-garde Jazz", "Bollywood",
    "Acid House", "Boogie", "Dungeon Synth", "Marches", "Renaissance", "Minimal Techno",
    "Musique Concrète", "Sludge Metal", "Electric Blues", "Mod", "Mambo", "Nu-Disco", "Chiptune",
    "Bossanova", "Country Blues", "Bass Music", "Acid Jazz", "Freestyle", "Interview", "Thug Rap",
    "Tribal House", "Berlin-School", "Big Beat", "Math Rock", "Indian Classical", "Light Music",
    "Modal", "Calypso", "Psychedelic", "Chicago Blues", "Broken Beat", "Education", "Mandopop",
    "Neofolk", "Impressionist", "Ethereal", "Rocksteady", "Neo Soul", "Crust", "Afrobeat",
    "Operetta", "Guaracha", "Afro-Cuban", "Video Game Music", "Lounge", "Britpop", "Chillwave",
    "G-Funk", "Grime", "Goregrind", "Hip-House", "Ragtime", "Éntekhno", "Euro-Disco",
    "Melodic Death Metal", "Goa Trance", "Canzone Napoletana", "Gothic Metal", "Deep Techno",
    "Brass Band", "Lovers Rock", "Nursery Rhymes", "Psychobilly", "Symphonic Metal", "Dream Pop",
    "Neo-Romantic", "Tech Trance", "Rhythmic Noise", "Dialogue", "Medieval", "Son", "Cut-up/DJ",
    "Hard Techno", "K-pop", "Atmospheric Black Metal", "Pacific", "Organ", "Speedcore", "Twist",
    "Guaguancó", "Nordic", "Eurobeat", "Ragga", "Promotional", "Military", "New Jack Swing",
    "Honky Tonk", "Educational", "Ragga HipHop", "Space-Age", "City Pop", "Mariachi",
    "Melodic Hardcore", "Deathcore", "Political", "Fado", "Funk Metal", "Hands Up", "Romani",
    "Sound Collage", "Music Hall", "Acid Rock", "Hawaiian", "Soukous", "J-Rock", "Highlife",
    "Folk Metal", "Soca", "Reggaeton", "Anison", "Freetekno", "Zouk", "Makina", "Witch House",
    "Afro-Cuban Jazz", "Noisecore", "Horrorcore", "Speech", "Monolog", "Post-Metal", "Jazzdance",
    "Piano Blues", "Delta Blues", "Vallenato", "Modern Electric Blues", "Coldwave", "Luk Thung",
    "Norteño", "Public Broadcast", "Bubblegum", "Electroacoustic", "Cubano", "New Beat", "Forró",
    "Corrido", "Italo House", "Gypsy Jazz", "Alt-Pop", "Bhangra", "Enka", "Alternative Metal",
    "No Wave", "Sound Art", "Viking Metal", "Therapy", "Harmonica Blues", "Porro", "Jumpstyle",
    "Texas Blues", "Boogaloo", "Noise Rock", "Cajun", "Special Effects", "Oratorio",
    "Speed Garage", "Pub Rock", "Industrial Metal", "Yé-Yé", "Andean Music", "Cloud Rap",
    "Tejano", "Post-Modern", "Karaoke", "Hillbilly", "Depressive Black Metal", "P.Funk",
    "Jump Blues", "Power Violence", "Pachanga", "Illbient", "Groove Metal", "Bassline",
    "Rebetiko", "Technical Death Metal", "Cantopop", "Descarga", "Orchestra", "Guajira",
    "Chinese Classical", "Boogie Woogie", "Raï", "Screw", "Dansband", "Donk", "Beguine",
    "Son Montuno", "Louisiana Blues", "Deathrock", "Hokkien Pop", "Nueva Cancion", "Séga",
    "Min'yō", "Symphony", "Russian Pop", "Latin Pop", "Charanga", "Western Swing",
    "Concert Film", "Jangle Pop", "Copla", "Horror Rock", "Crunk", "Klezmer", "Juke",
    "Sermon", "Levenslied", "Aboriginal", "Carnatic", "Pasodoble", "Compas", "Technical",
    "Catalan Music", "Cantata", "Electroclash", "DJ Battle Tool", "Ethno-pop", "Disco Polo",
    "Bachata", "Appalachian Music", "Tropical House", "Concerto", "Health-Fitness",
    "Conjunto", "Danzon", "Ghetto", "Música Criolla", "Funeral Doom Metal", "Népzene",
    "Progressive Breaks", "Halftime", "Huayno", "Turntablism", "Minneapolis Sound",
    "Sea Shanties", "Swingbeat", "Musette", "Chamber Music", "Batucada", "Indo-Pop",
    "Pornogrind", "Zydeco", "Bounce", "Bayou Funk", "Free Funk", "Keyboard", "Balearic",
    "Quechua", "Bakersfield Sound", "Footwork", "Dark Electro", "Early", "Ballet", "Cretan",
    "Liscio", "J-Core", "Lambada", "Steel Band", "Baião", "Sonata", "Sound Poetry",
    "Swamp Pop", "Go-Go", "Doomcore", "Choro", "Axé", "Schranz", "Movie Effects", "Skiffle",
    "Miami Bass", "Music Video", "Plunderphonics", "Ghetto House", "Pipe & Drum",
    "Glitch Hop", "Plena", "Ghazal", "Hyperpop", "Bleep", "Gamelan", "Kwaito", "Cabaret",
    "Erotic", "Zarzuela", "Kolo", "Mizrahi", "Chamamé", "Ryūkōka", "Persian Classical",
    "Zamba", "Samba-Canção", "Ottoman Classical", "Sertanejo", "Mo Lam", "Nueva Trova",
    "Unblack Metal", "Trova", "Baroque Pop", "NDW", "Basque Music", "Chacarera",
    "Barbershop", "Crossover thrash", "Bengali Music", "Blackgaze", "Gaita",
    "Future House", "Exotica", "Spirituals", "UK Street Soul", "Britcore", "Phonk",
    "Public Service Announcement", "Sunshine Pop", "Rock Opera", "Dangdut",
    "Group Sounds", "Neo Trance", "K-Rock", "Drill", "Chutney", "String Ensemble",
    "Memphis Blues", "Beatdown", "Occitan", "Ghettotech", "Qawwali", "Future Bass",
    "Joropo", "Luk Krung", "Favela Funk", "Tamil Film Music", "Reggae Gospel",
    "Nhạc Vàng", "Twelve-tone", "East Coast Blues", "Shidaiqu", "Slowcore",
    "Marimba", "Banda", "Villancicos", "Gusle", "Kaseko", "Andalusian Classical",
    "Ambient House", "Suite", "Keroncong", "Hyphy", "Timba", "Guarania",
    "Dub Poetry", "Dark Jazz", "UK Funky", "Izvorna", "Morna", "Milonga",
    "Piedmont Blues", "Hiplife", "Mathcore", "Cape Jazz", "Caipira",
    "French House", "Jibaro", "Maloya", "Toasting", "Baltimore Club",
    "Medical", "Overtone Singing", "Electro Swing", "Mento", "Sephardic",
    "Jota", "Deconstructed Club", "Vaudeville", "Marcha Carnavalesca",
    "Vocaloid", "Galician Traditional", "Salegy", "Lento Violento",
    "Post-Grunge", "Bomba", "Griot", "Mbalax", "Comfy Synth", "Zemer Ivri",
    "Screamo", "Phleng Phuea Chiwit", "Hard Beat", "Jersey Club",
    "Memphis Rap", "Beatbox", "Candombe", "Aguinaldo",
    "Brutal Death Metal", "Serial", "Bambuco", "Mugham", "Stride",
    "Nerdcore Techno", "Thai Classical", "Serenade", "Madrigal",
    "Ballroom", "Shaabi", "Cantorial", "Champeta", "Funaná",
    "Art Song", "Hypnagogic pop", "Microhouse", "Gagaku", "Cuatro",
    "Skweee", "Carimbó", "Bouncy Techno", "Sámi Music", "Seresta",
    "Arabic Pop", "Future Pop", "Kizomba", "Philippine Classical",
    "Occult", "Overture", "Jug Band", "Sonero", "Moombahton",
    "Yemenite Jewish", "Gwo Ka", "Solo", "Geet", "Hyper Techno",
    "Break-In", "Funkot", "Frevo", "Progressive Bluegrass",
    "Mass", "Waiata", "Cobla", "Lullaby",
    "Theme With Variations", "Néo Kyma", "Junkanoo",
    "Hill Country Blues", "Midwest Emo", "Rune Singing", "Bitpop",
    "Korean Court Music", "Taarab", "Lowercase", "Anarcho-Punk",
    "Filk", "Spiritual Jazz", "Manila Sound", "Piobaireachd",
    "Prelude", "V-pop", "Cambodian Classical", "Tamburitza",
    "Tone Poem", "Low Bap", "Bubbling", "Kuduro", "Euro Trance",
    "Rapso", "Pagode", "Gqom", "Guggenmusik", "Classical Guitar",
    "Nintendocore", "Neopagan", "Amapiano", "Synthpunk",
    "Rōkyoku", "Sean-nós", "Snap", "Lao Music", "Duranguense",
    "Fantasia", "Wind Ensemble", "Desert Blues", "Klasik",
    "Bangladeshi Classical", "Rhapsody", "Dances", "Anatolian Rock",
    "Etude", "Zhongguo Feng", "Għana", "Bongo Flava", "Shibuya-Kei",
    "Neo-Classical Metal", "Currulao", "Divertimento", "Antifolk",
    "Suomisaundi", "Incidental Music", "Nagauta", "Brega",
    "Requiem", "Percussion Ensemble", "Gnawa", "Motswako",
    "Plainchant", "Brit Pop", "Persian Pop", "Spaza", "Nocturne",
    "Azonto", "Yoruba", "Sokyoku", "Trallalero", "Jiuta", "Sport",
    "Minimalism", "Dabke", "Singeli", "Honkyoku", "Shomyo",
    "Concert Band", "Ojkača", "Atonal", "Bećarac", "Byzantine",
    "Baila", "Style Galant", "Expressionist", "Sankyoku",
    "Spectralism", "Rara", "Shinkyoku", "Shoegazer", "Khaliji",
    "Aleatoric", "Gogo", "Bultrón", "Kaskawi", "Futurism",
    "Microtonal",
]
