CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.import_runs (
    import_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('artists', 'labels', 'masters', 'releases')),
    source_file TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
    rows_loaded BIGINT NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS catalog.artists (
    artist_id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    real_name TEXT,
    profile TEXT,
    data_quality TEXT,
    urls TEXT[] NOT NULL DEFAULT '{}',
    name_variations TEXT[] NOT NULL DEFAULT '{}',
    aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    groups_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    members_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    images_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS catalog.labels (
    label_id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    contact_info TEXT,
    profile TEXT,
    data_quality TEXT,
    parent_label_id BIGINT,
    urls TEXT[] NOT NULL DEFAULT '{}',
    sublabels_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    images_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT labels_parent_fk
        FOREIGN KEY (parent_label_id)
        REFERENCES catalog.labels (label_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS catalog.masters (
    master_id BIGINT PRIMARY KEY,
    main_release_id BIGINT,
    title TEXT NOT NULL,
    year INTEGER,
    data_quality TEXT,
    genres_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    styles_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    artists_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    videos_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    images_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS catalog.releases (
    release_id BIGINT PRIMARY KEY,
    master_id BIGINT,
    title TEXT NOT NULL,
    status TEXT,
    year INTEGER,
    released TEXT,
    released_formatted TEXT,
    country TEXT,
    notes TEXT,
    data_quality TEXT,
    artists_sort TEXT,
    estimated_weight INTEGER,
    format_quantity INTEGER,
    thumb TEXT,
    uri TEXT,
    lowest_price NUMERIC(12, 2),
    num_for_sale INTEGER,
    have INTEGER,
    want INTEGER,
    community_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    companies_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    extraartists_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    images_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    videos_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT releases_master_fk
        FOREIGN KEY (master_id)
        REFERENCES catalog.masters (master_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS catalog.release_genres (
    release_id BIGINT NOT NULL,
    genre TEXT NOT NULL,
    PRIMARY KEY (release_id, genre),
    CONSTRAINT release_genres_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.release_styles (
    release_id BIGINT NOT NULL,
    style TEXT NOT NULL,
    PRIMARY KEY (release_id, style),
    CONSTRAINT release_styles_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.release_formats (
    release_id BIGINT NOT NULL,
    format_name TEXT NOT NULL,
    qty INTEGER,
    format_text TEXT,
    PRIMARY KEY (release_id, format_name),
    CONSTRAINT release_formats_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.release_format_descriptions (
    release_id BIGINT NOT NULL,
    format_name TEXT NOT NULL,
    description TEXT NOT NULL,
    PRIMARY KEY (release_id, format_name, description),
    CONSTRAINT release_format_desc_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE,
    CONSTRAINT release_format_desc_format_fk
        FOREIGN KEY (release_id, format_name)
        REFERENCES catalog.release_formats (release_id, format_name)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.release_artists (
    release_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    artist_id BIGINT,
    artist_name TEXT NOT NULL,
    anv TEXT,
    join_relation TEXT,
    role TEXT,
    tracks TEXT,
    PRIMARY KEY (release_id, position),
    CONSTRAINT release_artists_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE,
    CONSTRAINT release_artists_artist_fk
        FOREIGN KEY (artist_id)
        REFERENCES catalog.artists (artist_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS catalog.release_labels (
    release_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    label_id BIGINT,
    label_name TEXT NOT NULL,
    catalog_number TEXT,
    PRIMARY KEY (release_id, position),
    CONSTRAINT release_labels_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE,
    CONSTRAINT release_labels_label_fk
        FOREIGN KEY (label_id)
        REFERENCES catalog.labels (label_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS catalog.release_tracklist (
    release_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    sequence_text TEXT,
    track_type TEXT,
    title TEXT NOT NULL,
    duration TEXT,
    artists_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    extraartists_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    PRIMARY KEY (release_id, position),
    CONSTRAINT release_tracklist_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.release_identifiers (
    release_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    identifier_type TEXT NOT NULL,
    identifier_value TEXT,
    description TEXT,
    PRIMARY KEY (release_id, position),
    CONSTRAINT release_identifiers_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.release_companies (
    release_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    company_id BIGINT,
    company_name TEXT NOT NULL,
    entity_type INTEGER,
    entity_type_name TEXT,
    catalog_number TEXT,
    resource_url TEXT,
    PRIMARY KEY (release_id, position),
    CONSTRAINT release_companies_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.release_videos (
    release_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    title TEXT,
    description TEXT,
    uri TEXT NOT NULL,
    duration_seconds INTEGER,
    embed BOOLEAN,
    PRIMARY KEY (release_id, position),
    CONSTRAINT release_videos_release_fk
        FOREIGN KEY (release_id)
        REFERENCES catalog.releases (release_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS catalog.master_version_counts (
    master_id BIGINT PRIMARY KEY,
    version_count INTEGER NOT NULL,
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT master_version_counts_master_fk
        FOREIGN KEY (master_id)
        REFERENCES catalog.masters (master_id)
        ON DELETE CASCADE
);

GRANT USAGE ON SCHEMA catalog TO discogs_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA catalog TO discogs_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA catalog TO discogs_app;
