create table if not exists public.user_searches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  summary text not null,
  filters jsonb not null,
  status text not null default 'running',
  result_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_searches_status_check check (status in ('running', 'completed', 'aborted', 'failed'))
);

create index if not exists user_searches_user_created_idx
on public.user_searches (user_id, created_at desc);

alter table public.user_searches enable row level security;

create or replace function public.handle_user_searches_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_searches_timestamp on public.user_searches;

create trigger set_user_searches_timestamp
before update on public.user_searches
for each row
execute function public.handle_user_searches_timestamp();

drop policy if exists "Users can read own searches" on public.user_searches;
create policy "Users can read own searches"
on public.user_searches
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own searches" on public.user_searches;
create policy "Users can insert own searches"
on public.user_searches
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own searches" on public.user_searches;
create policy "Users can update own searches"
on public.user_searches
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own searches" on public.user_searches;
create policy "Users can delete own searches"
on public.user_searches
for delete
to authenticated
using (auth.uid() = user_id);
